baseURL = "https://example.com/"
title   = "hugo-mod-alpinejs"

# Only home for now, remove what you want.
disableKinds = [
	"taxonomy",
	"term",
	"404",
	"page",
	"robotstxt",
	"rss",
	"section",
	"sitemap",
]

[module]
	workspace = "hugo.work"
	[[module.imports]]
		path = "github.com/gohugoio/hugo-mod-alpinejs"
