baseURL = "https://example.com/"
title   = "hugo-mod-alpinejs"

# Only home for now, remove what you want.
disableKinds = [
	"taxonomy",
	"term",
	"404",
	"page",
	"robotstxt",
	"rss",
	"section",
	"sitemap",
]

[module]
	workspace = "hugo.work"

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/anchor/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/collapse/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/focus/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/intersect/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/mask/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/morph/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/persist/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/resize/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/sort/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/alpinejs/v3'

	[[module.imports]]
		path = 'github.com/gohugoio/hugo-mod-alpinejs/imacrayon/alpine-ajax'
